<a href="https://colab.research.google.com/github/arka19das/ML/blob/master/LINREG.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Linear Regression Implemented Example
## Here We are Implementing Linear Regression on the dataset of insurance pridecting the cost of the insurance
### Importing all the important libraries

In [0]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import random
alpha = 0.1

In [0]:
def calculateCost(X,Y,theta):
    (m,n) = X.shape
    H = X.dot(theta)
    J = sum((H-Y)**2/2/m)
    return J

In [0]:
data = pd.read_csv('/home/shivanshu/Desktop/ML_implementation/insurance.csv')
data = data.replace('female',1)
data = data.replace('male',0)
data = data.replace('yes',1)
data = data.replace('no',0)
data = data.drop("region",axis=1)
(m,n) = data.shape
test = data[int(m*0.8):m].to_numpy()
train = data[:int(m*0.8)].to_numpy()

MessageError: ignored

In [0]:
# train = np.hstack((train,train**2))
Y = train[:,-1:]
X = train[:,:-1]
X = np.hstack((X,X**2))
mean = X.mean(axis=0)
var = X.var(axis=0)
X = (X-mean)/var
(m,n) = X.shape
temp = np.ones(m)
temp = temp.reshape(m,1)
X = np.append(temp,X,axis=1)
Ymean = Y.mean(axis=0)
Yvar = Y.var(axis=0)
Y = (Y-Ymean)/Yvar

Ytest = test[:,-1:]
Xtest = test[:,:-1]
Xtest = np.hstack((Xtest,Xtest**2))
Xtest = (Xtest-mean)/var
(m,n) = Xtest.shape
temp = np.ones(m)
temp = temp.reshape(m,1)
Xtest = np.append(temp,Xtest,axis=1)
Ytest = (Ytest-Ymean)/Yvar

In [0]:
theta = np.random.randn(n+1,1)

In [0]:
thetaN = np.linalg.pinv((np.transpose(X))@X)@(np.transpose(X))@Y
print(thetaN)
calculateCost(X,Y,thetaN)

[[-9.40115582e-20]
 [-9.23491145e-05]
 [ 1.96042731e-07]
 [ 1.93450901e-04]
 [ 1.30838297e-05]
 [ 1.31458310e-05]
 [ 3.64584658e-02]
 [ 1.96034897e-07]
 [-7.17133638e-03]
 [-2.71626325e-05]
 [ 1.31458364e-05]]


array([8.60408339e-10])

In [0]:
# cost = calculateCost(X,Y,theta)
# costs =[cost]
# for i in range(15000):
#     (m,n) = X.shape
#     update = ((np.transpose(X@theta-Y))@X).reshape(n,1)*alpha/m
#     theta = theta - update
#     cost = calculateCost(X,Y,theta)
#     costs.append(cost)
#     print(cost)
#     print(theta)
#     if i>2 and costs[-2]<cost:
#         print("DIVERGING")
#         break

# plt.plot(costs)
# plt.ylabel('cost')
# plt.xlabel('iteration')
# plt.show()

In [0]:
Htest = Xtest.dot(thetaN)
err = sum((Htest-Ytest)**2)/2/m
print(err) #test error

[8.64655949e-10]


In [0]:
def predict(A,theta):
    # print(A)
    # A = (A-mean)/var
    # print(A.shape)
    return (np.transpose(A))@theta

In [0]:
age,sex,bmi,children,smoker = 42,1,40.37,2,1
listp = [age,sex,bmi,children,smoker,age**2,sex**2,bmi**2,children**2,smoker**2]
listp = (listp - mean)/var
A = np.array(listp)
lis = [1]
b = np.array(lis)
b = b.reshape(1,1)
A = A.reshape(10,1)
# print(b.shape,A.shape)
A = np.append(b,A,axis=0)
predict(A,thetaN)*Yvar + Ymean

array([[35813.304303]])