<a href="https://colab.research.google.com/github/arka19das/ML/blob/master/Trying_out_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
#practicing torch
from __future__ import print_function
import torch
import numpy as np
import scipy 
import torchvision.transforms as transforms
import torch.nn.functional as F
import matplotlib.pyplot as plt
import sys
import os

In [0]:
x=torch.empty((5,3))

In [0]:
print(x)

tensor([[1.4057e-35, 0.0000e+00, 3.3631e-44],
        [0.0000e+00,        nan, 0.0000e+00],
        [1.1578e+27, 1.1362e+30, 7.1547e+22],
        [4.5828e+30, 1.2121e+04, 7.1846e+22],
        [9.2198e-39, 7.0374e+22, 0.0000e+00]])


In [0]:
y=torch.zeros(5,3,dtype=torch.long)
print(y)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [0]:
a=[1,1 ,1.5,2.0,2.5,8.0]
b=(torch.tensor(a))
print(b,a)

tensor([1.0000, 1.0000, 1.5000, 2.0000, 2.5000, 8.0000]) [1, 1, 1.5, 2.0, 2.5, 8.0]


In [0]:
 y=x.new_ones(4, 6, dtype=torch.double)      # new_* methods take in sizes
print(y)

x = torch.randn_like(y, dtype=torch.float)    # override dtype!
print(x)          

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]], dtype=torch.float64)
tensor([[-0.1995,  0.8998, -0.7475, -1.3316, -2.7444,  2.1686],
        [ 0.9940,  0.3600, -0.8788, -0.3596,  1.6213,  0.8561],
        [-1.4924, -1.4690,  0.9678, -0.3783,  2.2513,  0.3874],
        [-0.2509, -0.8962,  0.5396,  0.8538,  0.7624,  0.8320]])


In [0]:
print(x.size())

torch.Size([4, 6])


In [0]:
torch.add(x,y)
torch.add(x,y,out=None)

tensor([[ 0.8005,  1.8998,  0.2525, -0.3316, -1.7444,  3.1686],
        [ 1.9940,  1.3600,  0.1212,  0.6404,  2.6213,  1.8561],
        [-0.4924, -0.4690,  1.9678,  0.6217,  3.2513,  1.3874],
        [ 0.7491,  0.1038,  1.5396,  1.8538,  1.7624,  1.8320]],
       dtype=torch.float64)

In [0]:
a=x.numpy()

In [0]:

x.add_(1)

tensor([[ 0.8005,  1.8998,  0.2525, -0.3316, -1.7444,  3.1686],
        [ 1.9940,  1.3600,  0.1212,  0.6404,  2.6213,  1.8561],
        [-0.4924, -0.4690,  1.9678,  0.6217,  3.2513,  1.3874],
        [ 0.7491,  0.1038,  1.5396,  1.8538,  1.7624,  1.8320]])

In [0]:
b=torch.from_numpy(a)
print(b)

tensor([[ 0.8005,  1.8998,  0.2525, -0.3316, -1.7444,  3.1686],
        [ 1.9940,  1.3600,  0.1212,  0.6404,  2.6213,  1.8561],
        [-0.4924, -0.4690,  1.9678,  0.6217,  3.2513,  1.3874],
        [ 0.7491,  0.1038,  1.5396,  1.8538,  1.7624,  1.8320]])


In [0]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
device = torch.device("cuda")          # a CUDA device object
y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
x = x.to(device)                       # or just use strings ``.to("cuda")``
z = x + y
print(z)
print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!

tensor([[ 1.8005,  2.8998,  1.2525,  0.6684, -0.7444,  4.1686],
        [ 2.9940,  2.3600,  1.1212,  1.6404,  3.6213,  2.8561],
        [ 0.5076,  0.5310,  2.9678,  1.6217,  4.2513,  2.3874],
        [ 1.7491,  1.1038,  2.5396,  2.8538,  2.7624,  2.8320]],
       device='cuda:0')
tensor([[ 1.8005,  2.8998,  1.2525,  0.6684, -0.7444,  4.1686],
        [ 2.9940,  2.3600,  1.1212,  1.6404,  3.6213,  2.8561],
        [ 0.5076,  0.5310,  2.9678,  1.6217,  4.2513,  2.3874],
        [ 1.7491,  1.1038,  2.5396,  2.8538,  2.7624,  2.8320]],
       dtype=torch.float64)


In [0]:
import torch 
import torch.nn as nn

import torch.nn.functional as F

class Net(nn.Module):

    def __init__(self):
        super(Net, self).__init__()
        # 1 input image channel, 6 output channels, 3x3 square convolution
        # kernel
        self.conv1 = nn.Conv2d(1, 6, 3)
        self.conv2 = nn.Conv2d(6, 16, 3)
        # an affine operation: y = Wx + b
        self.fc1 = nn.Linear(16 * 6 * 6, 120)  # 6*6 from image dimension
        self.fc2 = nn.Linear(120, 84)
        self.fc3 = nn.Linear(84, 10)

    def forward(self, x):
        # Max pooling over a (2, 2) window
        x = F.max_pool2d(F.relu(self.conv1(x)), (2, 2))
        # If the size is a square you can only specify a single number
        x = F.max_pool2d(F.relu(self.conv2(x)), 2)
        x = x.view(-1, self.num_flat_features(x))
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x

    def num_flat_features(self, x):
        size = x.size()[1:]  # all dimensions except the batch dimension
        num_features = 1
        for s in size:
            num_features *= s
        return num_features


net = Net()
print(net)

Net(
  (conv1): Conv2d(1, 6, kernel_size=(3, 3), stride=(1, 1))
  (conv2): Conv2d(6, 16, kernel_size=(3, 3), stride=(1, 1))
  (fc1): Linear(in_features=576, out_features=120, bias=True)
  (fc2): Linear(in_features=120, out_features=84, bias=True)
  (fc3): Linear(in_features=84, out_features=10, bias=True)
)


In [0]:
params = list(net.parameters())
print(len(params))
print(params[0].size())  # conv1's .weight
input = torch.randn(1, 1, 32, 32)
out = net(input)
print(out)

10
torch.Size([6, 1, 3, 3])
tensor([[ 0.1023,  0.0751,  0.0029, -0.0214,  0.0601,  0.1096, -0.0402, -0.0007,
          0.0696,  0.0101]], grad_fn=<AddmmBackward>)


In [0]:
net.zero_grad()
out.backward(torch.randn(1, 10))
output = net(input)
target = torch.randn(10)  # a dummy target, for example
target = target.view(1, -1)  # make it the same shape as output
criterion = nn.MSELoss()

loss = criterion(output, target)
print(loss)

tensor(1.4177, grad_fn=<MseLossBackward>)


In [0]:
print(loss.grad_fn)  # MSELoss
print(loss.grad_fn.next_functions[0][0])  # Linear
print(loss.grad_fn.next_functions[0][0].next_functions[0][0])  # ReLU

In [0]:
net.zero_grad()     # zeroes the gradient buffers of all parameters

print('conv1.bias.grad before backward')
print(net.conv1.bias.grad)

loss.backward()

print('conv1.bias.grad after backward')
print(net.conv1.bias.grad)

conv1.bias.grad before backward
tensor([0., 0., 0., 0., 0., 0.])
conv1.bias.grad after backward
tensor([-0.0039,  0.0074,  0.0106,  0.0004,  0.0172, -0.0068])


In [0]:
learning_rate = 0.01
for f in net.parameters():
    f.data.sub_(f.grad.data * learning_rate)

In [0]:
import torch.optim as optim

# create your optimizer
optimizer = optim.SGD(net.parameters(), lr=0.01)

# in your training loop:
optimizer.zero_grad()   # zero the gradient buffers
output = net(input)
loss = criterion(output, target)
loss.backward()
optimizer.step()    # Does the update